name: CI Pipeline

on:
  pull_request:
    branches:
    - '**' # Run on all branches for pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run linter (ESLint)
      run: npm run lint

    - name: Run formatter (Prettier)
      run: npm run prettier

    - name: Run tests (Jest)
      run: CI=true npm run test

    - name: Build
      run: npm run build
